Skeleton\Domain\Entity\User:
  type: entity
  repositoryClass: Skeleton\Infrastructure\Repository\UserRepository
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 36
    email:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    rememberToken:
      type: string
      length: 255
      nullable: true
      column: remember_token
    rememberIdentifier:
      type: string
      length: 255
      column: remember_identifier
    isEnabled:
      type: string
      columnDefinition: ENUM('0', '1')
      column: is_enabled
    confirmationToken:
      type: string
      length: 255
      column: confirmation_token